spring:
  cloud:
    gateway:
      default-filters:

      routes:
        - id: admin
          uri: http://localhost:4000
          predicates:
            - Path=/admin/**
          filters:
            -StripPrefix=1